### ISSUE TITLE
Json pops up when I view the results

### ISSUE THREAD

**Issue by Makimars** [Committing/MBTI.ai_public#1]
Don't know if it's bug or feature or both, but when I viewed the results, it showed JSON at the top.

with this at the end

`
/var/www/mbti.ai/httpdocs/templates/results.php
Line: 28
`

**Comment by Committing** [comment]
Hi Mak

We're still working on the mbti test still so the results are being dumped on the page regardless of styling. Thanks for letting me know the path was showing which isn't great but I'm not too fussed.

Thanks

**Comment by Committing** [comment]
It looks a little cleaner for now :) @Makimars
